kantha/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('login/', views.login_admin, name='login'),
    path('kantha/', views.dashboard, name='dashboard'),
    path('users/', include("users.urls", namespace="users")),

]

if(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views 


app_name = 'users'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.userlist, name='list'),
    path('pending/', views.userinactivelist, name='pending'),
    path('list/', views.userlist, name='active'),
    path('active/<int:id>', views.makeactive, name='makeactive'),
    path('inactive/<int:id>', views.makeinactive, name='makeinactive'),
    path('edit/<int:id>', views.edituser, name='edit'),
    path('edit/type/<str:value>', views.get_type, name='type'),
    path('update/<int:pk>', views.update, name='update'),
    path('detail/<int:pk>', views.UserDetail.as_view(), name='detail'),
    path('delete/<int:pk>', views.UserDelete.as_view(), name='delete'),
    path('relation/<int:pk>', views.addrelation, name='relation'),
    path('relation/usersautocomp/', views.get_user_auto, name='autocomp'),
    path('relation/add/<int:id>', views.user_relation, name='addrelation'),
] 

kantha/models.py
from django.db import models
from django.urls import reverse

class Administrator(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)

    def __str__(self):
        return self.username
    

users/models.py
from django.db import models

class Users(models.Model):
    uniqueuserid = models.CharField(max_length=20);
    name = models.CharField(max_length=30);
    password = models.CharField(max_length=20);
    photo = models.ImageField(upload_to='images', blank=True);
    dob = models.CharField(max_length=10);
    village = models.CharField(max_length=20);
    businesscat = models.CharField(max_length=20);
    businesstype = models.CharField(max_length=20);
    subsurname = models.CharField(max_length=20);
    activestatus = models.CharField(max_length=2);
        
    def __str__(self):
        return self.uniqueuserid;
 
class Villages(models.Model):
    villagename = models.CharField(max_length=30, default="")
    
class Gotra(models.Model):
    gotraname = models.CharField(max_length=30, default="")
    
class BusinessType(models.Model):
    business_name = models.CharField(max_length=30, default="")
    businesscatid = models.CharField(max_length=3, default="")
       
class BusinessCategory(models.Model):
    businesscategory = models.CharField(max_length=30, default="")  
    
class FamilyTree(models.Model):
    parentid = models.CharField(max_length=20)
    childid = models.CharField(max_length=20)   
    relation = models.CharField(max_length=10, default="")
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

kantha/forms.py
from django import forms

class AdminForm(forms.Form):
    username = forms.CharField(label="Username",widget=forms.TextInput(attrs={'placeholder': 'Username'}), max_length=20)
    password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'placeholder': 'Password:'}),max_length=20)

kantha/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic
from . import forms
from . import models

def index(request):
    form = forms.AdminForm()
    return render(request, "index.html", {'form':form})
    
def login_admin(request):
    username = request.POST.get('username')
    password = request.POST.get("password")

    if(username == "pratik" and password == "password"):
        return redirect(reverse('dashboard'))
    else:
        form = forms.AdminForm()
        return render(request, "index.html",{'form':form})

def dashboard(request):
    return render(request, "header.html")

users/views.py
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.views import generic
from users.models import Users, Villages, Gotra, BusinessCategory, BusinessType, FamilyTree
from django.http import HttpResponse
import json as simplejson
from django.core.files.storage import FileSystemStorage

def userinactivelist(request):
     all_users = Users.objects.filter(activestatus = '0')  
     return render(request, "users/users_list.html", {
        'users':all_users
    })
    
def userlist(request):
    all_users = Users.objects.filter(activestatus = '1')  
    return render(request, "users/users_list.html", {
        'users':all_users
    })
    
def edituser(request, id):
    user = Users.objects.get(id = id )
    villages = Villages.objects.all()
    gotra = Gotra.objects.all()
    businesscategory = BusinessCategory.objects.all()
    id = BusinessCategory.objects.filter(businesscategory=user.businesscat).values('id')[0];
    businesstype = (BusinessType.objects.filter(businesscatid = id.get('id')))
    return render(request, "users/users_edit.html", {
        'user':user,
        'villages':villages,
        'gotra':gotra,
        'businesscategory':businesscategory,
        'businesstype':businesstype,
    })
    
def get_type(request, value):
    id = BusinessCategory.objects.filter(businesscategory=value).values('id')[0];
    business_name = list(BusinessType.objects.filter(businesscatid = id.get('id')))
    return HttpResponse(simplejson.dumps(business_name,default=lambda o: o.__dict__, 
            sort_keys=True, indent=4), content_type="application/json")

def update(request, pk): 
    user = Users.objects.get(id = pk)
    name = request.POST.get("name")
    gotra = request.POST.get("gotra")
    dob = request.POST.get("dob")
    village = request.POST.get("village")
    password = request.POST.get("password")
    bcat = request.POST.get("businesscategory")
    btype = request.POST.get("businesstype")
    image = request.POST.get('imagestring')
    if(image != ""):
        uploaded_file = request.FILES['imagestring']
        fs = FileSystemStorage()
        fs.save(image, uploaded_file)
        user.photo = uploaded_file.name
                
    user.name = name
    user.subsurname = gotra
    user.dob = dob
    user.village = village
    user.password = password
    user.businesscat = bcat
    user.businesstype = btype
    
    user.save()
    
    return redirect(reverse('users:list'))

class UserDetail(generic.DetailView):
    model = Users
    
class UserDelete(generic.DeleteView):
    model = Users
    success_url = reverse_lazy('users:list')

def makeactive(request, id):
    user = Users.objects.get(id = id )
    user.activestatus = 1
    user.save()
    return redirect(reverse('users:pending'))
       
def makeinactive(request, id):
    user = Users.objects.get(id = id )
    user.activestatus = 0
    user.save()
    return redirect(reverse('users:list'))

def addrelation(request, pk):
    user = Users.objects.get(id = pk)
    return render(request, "users/add_relation.html", {
        'user':user
    })

def get_user_auto(request):
    user_list = list(Users.objects.all())
    return HttpResponse(simplejson.dumps(user_list,default=lambda o: o.__dict__, 
            sort_keys=True, indent=4), content_type="application/json")

def user_relation(request, id):
    user = Users.objects.get(id=id)
    familytree = FamilyTree()
    familytree.parentid = user.uniqueuserid
    familytree.childid = request.POST.get('child')
    familytree.relation = request.POST.get('relation')
    familytree.save()
    
    return redirect(reverse('users:active'))

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Kantha</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- Latest compiled and minified JavaScript -->
    
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'kantha/css/master.css'%}">


  </head>


  <body>

    <div class="mycontent" style="background: white">
            
        {% block content %}
    
        
        {% endblock %}
    
    </div>

  </body>

<!-- <script src="{% static "social_media/js/master.js" %}" type="text/javascript" ></script> -->

</html>

templates/header.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

    <nav class="navbar fixed-top navbar-light">
        <a class="navbar-brand" href="{% url 'dashboard' %}" style="font-size:2rem">
            <img class="logo_nav" src="{% static 'kantha/images/logo.png'%}">
            Kantha
        </a>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link logout" href="#">Logout</a>
            </li>
        </ul>
    </nav>

    <div class="horizontal">
    <nav class="sidenav nav flex-column">
        <a class="nav-link" href="#">
            <i class="fas fa-home"></i>
            Dashboard
        </a>
        <a class="nav-link" href="{% url 'users:list' %}">
            <i class="fas fa-users"></i>
            Active Users
        </a>
        <a class="nav-link" href="{% url 'users:pending' %}">
            <i class="fas fa-user-lock"></i>
            Pending Activation
        </a>
        <a class="nav-link" href="#">
            <i class="fas fa-user-plus"></i>
            Register New
        </a>
        <a class="nav-link" href="#">
            <i class="fas fa-image"></i>
            Header Banner Images
        </a>
        <a class="nav-link" href="#">
            <i class="far fa-image"></i>
            Footer Banner Images
        </a>
        <a class="nav-link" href="#">
            <i class="fas fa-bell"></i>
            Broadcast
        </a>
    </nav>
    
    <div class= "sidenavcontent">
       
        {% block dashContent %}

        {% endblock %}
    
    </div>

    </div>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
    <div class="card text-white bg-dark mb-3 mx-auto text-center justify-content-center" style="max-width: 30rem;margin-top:8rem">
        <div class="card-header" style="font-size: 3rem">Kantha</div>
        <div class="card-body">
            <form method="POST" action="/login/">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-primary btn-lg" style="margin-top: 1rem">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

users/templates/users/add_relation.html
{% extends "users/users_base.html" %}
{% load bootstrap4 %}
{% comment %} form to add relation {% endcomment %}

{% block userlist %}

<div class="container">
<form method="POST" action="{% url 'users:addrelation' id=user.id %}">
    {% csrf_token %}
    <div class="container">
    <h3>Add Relation</h3>
    <label>User: {{ user.uniqueuserid }} </label>
    </div>
    <div class="container">
    <label>Who do you wanna add?</label>
    <input type="text" class="form-control" autocomplete="on" name="child" id="childid"/>
    </div>
    <div class="container">
    <select name="relation" class="form-control">
      <option>Please select</option>
      <option value="Son">Son</option>
      <option value="Daughter">Daughter</option>
      <option value="Mother">Mother</option>
      <option value="Father">Father</option>
      <option value="Brother">Brother</option>
      <option value="Sister">Sister</option>
      <option value="Spouse">Spouse</option>
    </select>
    <button class="save btn btn-primary" type="submit" style="margin-top:2rem">ADD</button>
    </div>
</form>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.0/themes/smoothness/jquery-ui.css">
<script src="http://code.jquery.com/jquery-1.10.2.js"></script>
<script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script>
$(document).ready( function() {
  var request_url = "usersautocomp/";
  var availableTags = [];
  $.ajax({
          url: request_url,
          success: function(data){
          $.each(data, function(index, text){
            availableTags.push(text.uniqueuserid)
          })
  }
  })
  console.log(availableTags);
  $('#childid').autocomplete({
    source: availableTags
  });

});
</script>

{% endblock %}

users/templates/users/users_base.html
{% extends "header.html" %}

{% block dashContent %}

    {% block userlist %}


    {% endblock %}


{% endblock %}

users/templates/users/users_confirm_delete.html
{% extends "users/users_base.html" %}

{% block userlist %}
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete {{ object }}?</p>
        <input type="submit" value="Confirm" class="btn btn-danger">
    </form>
{% endblock %}

users/templates/users/users_detail.html
{% extends "users/users_base.html" %}

{% block userlist %}
<div class="jumbotron container viewdiv">
<img src="{{ users.photo.url }}" id="profileimage" width=300 height=300 class="center_image">
<div class="row">
<div class="col-4 horizontal_view">
    <label class="viewlabel">Name:</label>
     <p class="value">{{ users.name}}</p>
</div>
<div class="col-4 horizontal_view">
    <label class="viewlabel">User ID:</label>
    <p class="value">{{ users.uniqueuserid}}</p>
</div>
<div class="col-4 horizontal_view">
    <label class="viewlabel">Gotra:</label>
    <p class="value">{{ users.subsurname}}</p>
</div>
</div>
<div class="row">
    <div class="col-4 horizontal_view">
        <label class="viewlabel">Village:</label>
            <p class="value">{{ users.village}}</p>
    </div>
    <div class="col-4 horizontal_view">
        <label class="viewlabel">Date of birth:</label>
        <p class="value">{{ users.dob}}</p>
    </div>
    <div class="col-4 horizontal_view">
        <label class="viewlabel">Password:</label>
        <p class="value">{{ users.password}}</p>
    </div>
</div>
<div class="row">
    <div class="col-4 horizontal_view">
        <label class="viewlabel">Bus. Category:</label>
            <p class="value">{{ users.businesscat}}</p>
    </div>
    {% if users.businesstype != "" %}
        <div class="col-4 horizontal_view">
            <label class="viewlabel">Bus. Type:</label>
            <p class="value">{{ users.businesstype}}</p>
        </div>
    {% endif %}
</div>
</div>
{% endblock %}

users/templates/users/users_edit.html
{% extends "users/users_base.html" %}

{% block userlist %}
<form method="POST" action="{% url 'users:update' pk=user.id %}" enctype="multipart/form-data">
{% csrf_token %}
<div class="image_profile_div">
{% if user.photo %}
    <img src="{{ user.photo.url }}" width=250 height=250 id="profileimage" alt=""/>
{% endif %}
<input type="file" accept="image/*" name="imagestring" id="imageinput"/>
</div>

<div class="container">
<div class="row">
<div class="col">
<label>Name:</label>
<input type="text" name="name" required class="form-control" value="{{ user.name }}" />
</div>
<div class="col">
<label>Gotra</label>
        <select name="gotra" class="form-control">
        {% for got in gotra %}
            <option value="{{ got.gotraname }}"
            {% if user.subsurname == got.gotraname %}selected="selected"{% endif %}>
            {{ got.gotraname }}</option>
        {% endfor %}
        </select>
</div>
<div class="col">
<label>Date of Birth:</label>
<input type="date" data-format="DD-MM-YYYY" data-template="D MMM YYYY" class="form-control"  name="dob" value="{{ user.dob }}" />
</div>
</div>
</div>

<div class="container">
<div class="row">
<div class="col">
<label>Village:</label>
        <select name="village" class="form-control">
        {% for village in villages %}
            <option value="{{ village.villagename }}"
            {% if user.village == village.villagename %}selected="selected"{% endif %}>
            {{ village.villagename }}
            </option>
        {% endfor %}
        </select>
    </div>
<div class="col">
<label>Password:</label>
<input type="password" class="form-control"  name="password" value="{{ user.password }}" />
</div>
</div>
</div>

<div class="container">
<div class="row">
<div class="col-6">
<label>Business Category:</label>
        <select name="businesscategory" class="form-control" id="category">
            <option value="">Select Category</option>
        {% for category in businesscategory %}
           <option value="{{category.businesscategory}}"
            {% if user.businesscat == category.businesscategory %}selected="selected"{% endif %}>
            {{category.businesscategory}}
            </option>
        {% endfor %}
        </select>
</div>
<div class="col-6" id="type">
<label>Business Type:</label>
        <select name="businesstype" class="form-control">
            <option value="">Select Type</option>
            {% for type in businesstype %}
                <option value="{{type.business_name}}"
                    {% if user.businesstype == type.business_name %}selected="selected"{% endif %}>
                    {{type.business_name}}
                </option>
            {% endfor %}
        </select>
</div>
</div>
</div>

<button type="submit" class="btn btn-dark updateprofile">Submit</button>
</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
$("#category").change(function() {
var value = $(this).val();
if (value == 'Business' || value == 'Profession'){
    $('#type').show();
    $('select[name=businesstype]').empty();
    var request_url = "type/" + value;
    $.ajax({
            url: request_url,
            success: function(data){
            $.each(data, function(index, text){
                $('select[name=businesstype]').append(
                $('<option></option>').val(text.business_name).html(text.business_name));
            })
    }
    })
}
else 
    $('#type').hide();
});

$('#imageinput').change(function(e) {
    if ((this).files && (this).files[0]) {
    var reader = new FileReader();
    
    reader.onload = function(e) {
      $('#profileimage').attr('src', e.target.result);
    }
    
    reader.readAsDataURL((this).files[0]);
  }
});
</script>

{% endblock %}

users/templates/users/users_list.html
{% extends "users/users_base.html" %}

{% block userlist %}

    <table class="table">
    <thead class="thead-dark table-striped">
    <tr>
        <th scope="col" class="center">#</th>
        <th scope="col" class="center">Name</th>
        <th scope="col" class="center">ID</th>
        <th scope="col" class="center">Gotra</th>
        <th scope="col" class="center">Village</th>
        <th scope="col" class="center">Edit</th>
        <th scope="col" class="center">Relation</th>
        <th scope="col" class="center">View</th>
        <th scope="col" class="center">Delete</th>
        <th scope="col" class="center">Status</th>
    </tr>
    </thead>
    <tbody>
        {% for user in users  %}
            <tr>
                <th scope="row"  class="center">{{ forloop.counter }}</th>
                <td class="center">{{user.name}}</td>
                <td class="center">{{user.uniqueuserid}}</td>
                <td class="center">{{user.subsurname}}</td>
                <td class="center">{{user.village}}</td>
                <td class="center"><a href="{% url 'users:edit' id=user.id %}"><i class="fas fa-user-edit"></i></a></td>
                <td class="center"><a href="{% url 'users:relation' pk=user.id %}"><i class="far fa-plus-square"></i></a></td>
                <td class="center"><a href="{% url 'users:detail' pk=user.id %}"><i class="fas fa-street-view"></i></a></td>
                <td class="center"><a href="{% url 'users:delete' pk=user.id %}"><i class="far fa-trash-alt"></i></a></td>
                {% if user.activestatus == '1' %}
                    <td class="center"><a href="{% url 'users:makeinactive' id=user.id  %}"><i class="fas fa-check-circle"></i></a></td>
                {% else %}
                    <td class="center"><a href="{% url 'users:makeactive' id=user.id  %}"><i class="fas fa-times-circle"></i></a></td>
                {% endif %}
            </tr>
        {% endfor %}
    </tbody>
    </table>    
        
{% endblock %}